### PR TITLE
add light effects module

### PR DESCRIPTION
**Pull request by ellensp**
As requested in Issue https://github.com/derkalle4/python3-idotmatrix-library/issues/4 

Light effects where missing from the library

I logged and decoded the protocol from the app and added the new module.

This example is effect 0 with 7 colours

```
1c 00 03 02 00 5a 07 7f 00 00 7f 51 00 7f 7f 00 00 7f 00 00 00 7f 7f 00 7f 7f 7f 7f
|           |     |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
|           |     |  R1 G1 B1 R2 G2 B2 R3 G3 B3 R4 G4 B4 R5 G5 B5 R6 G6 B6 R7 G7 B7
|           |     ^count (RGB tupples) colours 2-7 
|           ^effect number 0-6
^count. full packet size inducing the count byte starting at 1
```

This example is effect 1 with 2 colours

```
0d 00 03 02 01 5a 02 7f 00 7f 7f 00 00
|           |     |  |  |  |  |  |  |
|           |     |  R1 G1 B1 R2 G2 B2
|           |     ^count (RGB tupples) colours 2-7 
|           ^effect number 0-6
^count. full packet size inducing the count byte starting at 1
```

I added a test_effect.py script to show all effects and to provide some examples on how to use the module.

Note: I'm not a python expert, this code was heavily based on other existing modules and I used copilot AI to get assistance.

Also note, I'm not an American. Colour is spelt correctly for my geographic region.

### CODE REVIEW

**Comment by derkalle4** [comment]
Hi @ellensp - can you please resolv the conflict? I will happily merge afterwards :)

**Comment by ellensp** [comment]
Updated and resolved

**Comment by ellensp** [comment]
@derkalle4 Please commit.

There is a new patch coming to fix uploading images see https://github.com/derkalle4/python3-idotmatrix-client/issues/50#issuecomment-2487618670

And I would rather not have to resolve more conflicts

**Comment by derkalle4** [comment]
@ellensp many thanks!

**Pull request merged**
