### PR TITLE
GIF: upload chunks individually

### PR DESCRIPTION
**Pull request by leromarinvit**
Uploading GIFs > 4096 bytes doesn't work - it seems the chunks must be sent in separate transfers.

With this change, all 1- and 2-chunk GIFs I've tried work now. But images with 3 or more chunks still cause problems, so something must be wrong still.

### CODE REVIEW

**Comment by derkalle4** [comment]
Hi @leromarinvit many thanks for your push-request. Sorry for the delay... I'll merge your commit as this seems working for me. Many thanks! :)

**Comment by derkalle4** [comment]
Btw the pull-request is marked as "work in progress". Please set it to "Ready for review" once I can push it.

**Comment by leromarinvit** [comment]
You're right, this is an improvement even in the current state, even if it's not perfect.

**Comment by derkalle4** [comment]
Many thanks @leromarinvit - I have integrated it. Whenever you have made additional progress feel free to hand in another pull-request :)

**Pull request merged**
